name: pytitle Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name:
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name:
        run: tox
      - name: Upload coverage
        uses: codecov/codecov-action@v2